name: Deploy with Docker Compose via SSH

on:
    push:
        branches: main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Deploy to server
              uses: appleboy/ssh-action@v1.2.2
              env:
                  BASE_URL: ${{ secrets.BASE_URL }}
                  GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
              with:
                  host: ${{ secrets.SERVER_HOST }}
                  username: ${{ secrets.SERVER_USER }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  port: ${{ secrets.SERVER_PORT || 22 }}
                  script: |
                      cd /opt/mini-ai-app-builder || exit 1

                      # 
                      if [ ! -d ".git" ]; then
                        git clone ${{ github.server_url }}/${{ github.repository }} .
                      else
                        git fetch origin
                        git reset --hard origin/${{ github.ref_name }}
                      fi

                      cat > .env << 'EOF'
                      BASE_URL=${{ secrets.BASE_URL }}
                      GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}
                      EOF

                      docker compose down
                      docker compose up -d --build
                      docker compose ps
